---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomato
  labels:
    app: tomato
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomato
  template:
    metadata:
      labels:
        app: tomato
    spec:
      containers:
      - name: tomato
        image: quay.io/pickledrick/tomato
        ports:
        - containerPort: 8081
      nodeSelector:
        sauce: tomato
---
kind: Service
apiVersion: v1
metadata:
  name: tomato
spec:
  selector:
    app: tomato
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bbq
  labels:
    app: bbq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bbq
  template:
    metadata:
      labels:
        app: bbq
    spec:
      containers:
      - name: bbq
        image: quay.io/pickledrick/bbq
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 1
      nodeSelector:
        sauce: bbq
---
kind: Service
apiVersion: v1
metadata:
  name: bbq
spec:
  selector:
    app: bbq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sss
  labels:
    app: sss
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sss
  template:
    metadata:
      labels:
        app: sss
    spec:
      containers:
      - name: sss
        env:
        - name: DEADLINE
          value: "3"
        image: quay.io/pickledrick/sss:good
        ports:
        - containerPort: 9091
      nodeSelector:
        kubernetes.io/role: master
---
kind: Service
apiVersion: v1
metadata:
  name: sss
  labels:
    app: sss
spec:
  selector:
    app: sss
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091
    name: app